### PR TITLE
Documentation Proposal

### PR DESCRIPTION
**Pull request by lordloki**
Basically, benefit from old page graphics with a new card format

image

Maybe is better to put all cards with same height, opinions??

### CODE REVIEW

**Comment by Aman-Anas** [comment]
I think having all cards the same height would look better, may have to shorten or lengthen some descriptions to do that though

**Comment by rpaladin** [comment]
Personally, I think the orange-corners should be symmetrical with the black-corners - But that's just my take ^^

# Example
image

**Comment by lordloki** [comment]
I add 3 options (6, 12 and 45 degrees), the 12 is the current one. The 45 degrees would need additional changes as the cards are not square.
6-degrees
12-degrees
45-degrees

**Comment by rpaladin** [comment]
Option #1 looks nice. Alternatively, I wonder if we could have some modern border-line animations implemented instead of corners.

# Example
https://codepen.io/Chester/pen/QPoyjN

**Comment by lordloki** [comment]
It is possible to add a gradient between the 2 oranges color too
image

**Comment by lordloki** [comment]
Ok, I'm going to commit as it is. We can modify it later if there is another better proposal

**Pull request merged**
